---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - controller.kubequant.com
  resources:
  - kubequantpodresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.kubequant.com
  resources:
  - kubequantpodresources/finalizers
  verbs:
  - update
- apiGroups:
  - controller.kubequant.com
  resources:
  - kubequantpodresources/status
  verbs:
  - get
  - patch
  - update
